@startuml
!include_many CracCreationContext.puml

CracCreationContext <|-- CsaProfileCracCreationContext

class CsaProfileCracCreationContext {
+ Set<CsaProfileElementaryCreationContext> getContingencyCreationContexts()
+ Set<CsaProfileElementaryCreationContext> getRemedialActionCreationContexts()
+ CsaProfileElementaryCreationContext getRemedialActionCreationContext(String nativeId)
+ Set<CsaProfileElementaryCreationContext> getCnecCreationContexts()
}

CsaProfileCracCreationContext "1" *--> "*" CsaProfileElementaryCreationContext

class CsaProfileElementaryCreationContext {
+ String getElementId()
+ String getElementName()
}

!include_many CracCreationContext.puml!ElementaryCreationContext

CsaProfileElementaryCreationContext --|> ElementaryCreationContext
@enduml