@startuml
!include_many CracCreationContext.puml
!include_many CracCreationContext.puml!ElementaryCreationContext

CracCreationContext <|-- CsaProfileCracCreationContext

class CsaProfileCracCreationContext {
+ Set<ElementaryCreationContext> getContingencyCreationContexts()
+ Set<ElementaryCreationContext> getRemedialActionCreationContexts()
+ ElementaryCreationContext getRemedialActionCreationContext(String nativeId)
+ Set<ElementaryCreationContext> getCnecCreationContexts()
}

CsaProfileCracCreationContext "1" *--> "*" ElementaryCreationContext
@enduml