@startuml
!include_many UcteCracCreationContext.puml!0
!include_many CracCreationContext.puml!ElementaryCreationContext
UcteCracCreationContext <|-- CseCracCreationContext

class CseCracCreationContext {
+ ElementaryCreationContext getOutageCreationContext(String outageName)
+ List<ElementaryCreationContext> getOutageCreationContexts()
}
CseCracCreationContext "1" *--> "*" ElementaryCreationContext
@enduml