@startuml
!include_many UcteCracCreationContext.puml!0
UcteCracCreationContext <|-- CseCracCreationContext

class CseCracCreationContext {
+ CseOutageCreationContext getOutageCreationContext(String outageName)
+ List<CseOutageCreationContext> getOutageCreationContexts()
}
CseCracCreationContext "1" *--> "*" CseOutageCreationContext

class CseOutageCreationContext {
+ String getCreatedContingencyId()
}

!include_many CracCreationContext.puml!ElementaryCreationContext
CseOutageCreationContext --|> ElementaryCreationContext 
@enduml