@startuml
!include_many CracCreationContext.puml!CracCreationContext
CracCreationContext <|-- UcteCracCreationContext

interface UcteCracCreationContext {
+ List<? extends BranchCnecCreationContext> getBranchCnecCreationContexts()
+ BranchCnecCreationContext getBranchCnecCreationContext(String branchCnecId)
+ List<? extends ElementaryCreationContext> getRemedialActionCreationContexts()
+ ElementaryCreationContext getRemedialActionCreationContext(String remedialActionId)
}
@enduml

@startuml
UcteCracCreationContext "1" *--> "*" BranchCnecCreationContext
UcteCracCreationContext "1" *--> "*" ElementaryCreationContext

interface BranchCnecCreationContext {
+ NativeBranch getNativeBranch()
+ boolean isBaseCase()
+ Optional<String> getContingencyId()
+ Map<String, String> getCreatedCnecsIds()
+ boolean isDirectionInvertedInNetwork()
}

BranchCnecCreationContext --|> ElementaryCreationContext

!include_many CracCreationContext.puml!ImportStatus
@enduml