/*
 *  Copyright (c) 2020, RTE (http://www.rte-france.com)
 * This Source Code Form is subject to the terms of the Mozilla Public
 *  License, v. 2.0. If a copy of the MPL was not distributed with this
 *  file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 */

package com.farao_community.farao.data.crac_io_json.serializers;

import com.farao_community.farao.data.crac_api.*;
import com.farao_community.farao.data.crac_api.cnec.Cnec;
import com.farao_community.farao.data.crac_api.cnec.FlowCnec;
import com.farao_community.farao.data.crac_api.network_action.NetworkAction;
import com.farao_community.farao.data.crac_api.range_action.HvdcRangeAction;
import com.farao_community.farao.data.crac_api.range_action.PstRangeAction;
import com.farao_community.farao.data.crac_io_json.ExtensionsHandler;
import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.powsybl.commons.json.JsonUtil;

import java.io.IOException;
import java.util.*;
import java.util.stream.Collectors;

import static com.farao_community.farao.data.crac_io_json.JsonSerializationConstants.*;

/**
 * @author Alexandre Montigny {@literal <alexandre.montigny at rte-france.com>}
 */
public class CracSerializer extends AbstractJsonSerializer<Crac> {

    private static final String CRAC_TYPE = "CRAC";
    private static final String CRAC_VERSION = "1.0";
    private static final String CRAC_INFO = "Generated by FARAO http://farao-community.github.io";

    @Override
    public void serialize(Crac crac, JsonGenerator gen, SerializerProvider serializers) throws IOException {
        gen.writeStartObject();

        gen.writeStringField(TYPE, CRAC_TYPE);
        gen.writeStringField(VERSION, CRAC_VERSION);
        gen.writeStringField(INFO, CRAC_INFO);
        gen.writeStringField(ID, crac.getId());
        gen.writeStringField(NAME, crac.getName());

        serializeNetworkElements(crac, gen);
        serializeContingencies(crac, gen);
        serializeFlowCnecs(crac, gen);
        serializePstRangeActions(crac, gen);
        serializeHvdcRangeActions(crac, gen);
        serializeNetworkActions(crac, gen);

        JsonUtil.writeExtensions(crac, gen, serializers, ExtensionsHandler.getExtensionsSerializers());

        gen.writeEndObject();
    }

    private void serializeNetworkElements(Crac crac, JsonGenerator gen) throws IOException {
        Map<String, String> networkElementsNamesPerId = new HashMap<>();

        // Get network elements from Cnecs
        crac.getCnecs().stream().map(Cnec::getNetworkElement)
                .filter(networkElement -> !networkElement.getId().equals(networkElement.getName()))
                .forEach(networkElement -> networkElementsNamesPerId.put(networkElement.getId(), networkElement.getName()));

        // Get network elements from Contingencies
        crac.getContingencies().stream().map(Contingency::getNetworkElements).flatMap(Set::stream)
                .filter(networkElement -> !networkElement.getId().equals(networkElement.getName()))
                .forEach(networkElement -> networkElementsNamesPerId.put(networkElement.getId(), networkElement.getName()));

        // Get network elements from RemedialActions
        for (RemedialAction<?> remedialAction : crac.getRemedialActions()) {
            remedialAction.getNetworkElements().stream().filter(networkElement -> !networkElement.getId().equals(networkElement.getName()))
                    .forEach(networkElement -> networkElementsNamesPerId.put(networkElement.getId(), networkElement.getName()));
        }

        // Write all
        gen.writeObjectField(NETWORK_ELEMENTS_NAME_PER_ID, networkElementsNamesPerId);
    }

    private void serializeContingencies(Crac crac, JsonGenerator gen) throws IOException {
        gen.writeArrayFieldStart(CONTINGENCIES);
        List<Contingency> sortedListOfContingencies = crac.getContingencies().stream()
                .sorted(Comparator.comparing(Contingency::getId))
                .collect(Collectors.toList());
        for (Contingency contingency : sortedListOfContingencies) {
            gen.writeObject(contingency);
        }
        gen.writeEndArray();
    }

    private void serializeFlowCnecs(Crac crac, JsonGenerator gen) throws IOException {
        gen.writeArrayFieldStart(FLOW_CNECS);
        List<FlowCnec> sortedListOfCnecs = crac.getFlowCnecs().stream()
                .sorted(Comparator.comparing(FlowCnec::getId))
                .collect(Collectors.toList());
        for (FlowCnec flowCnec : sortedListOfCnecs) {
            gen.writeObject(flowCnec);
        }
        gen.writeEndArray();
    }

    private void serializePstRangeActions(Crac crac, JsonGenerator gen) throws IOException {
        gen.writeArrayFieldStart(PST_RANGE_ACTIONS);
        List<PstRangeAction> sortedListPsts = crac.getPstRangeActions().stream()
                .sorted(Comparator.comparing(PstRangeAction::getId))
                .collect(Collectors.toList());
        for (PstRangeAction pstRangeAction : sortedListPsts) {
            gen.writeObject(pstRangeAction);
        }
        gen.writeEndArray();
    }

    private void serializeHvdcRangeActions(Crac crac, JsonGenerator gen) throws IOException {
        gen.writeArrayFieldStart(HVDC_RANGE_ACTIONS);
        List<HvdcRangeAction> sortedListHvdcs = crac.getHvdcRangeActions().stream()
                .sorted(Comparator.comparing(HvdcRangeAction::getId))
                .collect(Collectors.toList());
        for (HvdcRangeAction hvdcRangeAction : sortedListHvdcs) {
            gen.writeObject(hvdcRangeAction);
        }
        gen.writeEndArray();
    }

    private void serializeNetworkActions(Crac crac, JsonGenerator gen) throws IOException {
        gen.writeArrayFieldStart(NETWORK_ACTIONS);
        List<NetworkAction> sortedList = crac.getNetworkActions().stream()
                .sorted(Comparator.comparing(NetworkAction::getId))
                .collect(Collectors.toList());
        for (NetworkAction networkAction : sortedList) {
            gen.writeObject(networkAction);
        }
        gen.writeEndArray();
    }
}
