# Keys must be alphabetically ordered
openrao.pstregulation.reportContingencyScenariosToRegulate = ${nbContingencies} contingency scenario(s) to regulate: ${contingenciesList}
openrao.pstregulation.reportErrorDuringPstRegulation = An error occurred during PST regulation, pre-regulation RAO result will be kept. Error was: ${errorMessage}
openrao.pstregulation.reportPstCannotBeRegulated = PST ${pstId} cannot be regulated as no curative PST range action was defined for it.
openrao.pstregulation.reportPstRegulationTriggeredDueToOverloadedFlowCnec = FlowCNEC '${flowCnec}' of contingency scenario '${contingency}' is overloaded and is the most limiting element, PST regulation has been triggered: ${allShiftedPstsDetails}
openrao.pstregulation.reportPstsToRegulate = ${nbPsts} PST(s) to regulate: ${pstsList}
