name: Documentation

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  doc_ubuntu:
    name: ⚙️ Build documentation on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install Python dependencies
        run: |
          pip install --only-binary :all: sphinx==9.1.0
          pip install --only-binary :all: sphinx-tabs==3.5.0
          pip install --only-binary :all: furo==2025.12.19
          pip install --only-binary :all: myst-parser==5.1.0
          pip install --only-binary :all: sphinxcontrib-mermaid==2.0.2
          pip install --only-binary :all: sphinx_copybutton==0.5.2

      - name: Build doc
        run: sphinx-build -a docs ./build-docs

  broken_links_check:
    name: 🔗 Look for broken links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install markdown-link-check
        run: npm install --ignore-scripts -g markdown-link-check@3.13.7

      - name: Check all Markdown links
        run: |
          BROKEN_LINKS=$(markdown-link-check -q ./docs)
          if [ -n "$BROKEN_LINKS" ]; then
            echo "❌ Found broken links: $BROKEN_LINKS"
            exit 1
          else
            echo "✔️ No broken links found"
            exit 0
          fi
