name: Java files check

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  doc_ubuntu:
    name: ☕ Check Java files structure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Build doc
        run: python .github/workflows/scripts/java_file_format_checker.py
